AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  Event-driven AWS pipeline to chunk large PDFs, batch-process PII detection
  with Amazon Comprehend, and produce a fully redacted PDF plus redaction report.

Globals:
  Function:
    Runtime: python3.12
    Tracing: Active
    Architectures:
      - x86_64

Parameters:
  InputPrefix:
    Type: String
    Default: incoming/
    Description: S3 key prefix where source PDFs are uploaded.
  OutputPrefix:
    Type: String
    Default: redacted/
    Description: S3 key prefix where redacted PDFs are written.
  ReportPrefix:
    Type: String
    Default: reports/
    Description: S3 key prefix where JSON redaction reports are written.
  WorkPrefix:
    Type: String
    Default: work/
    Description: S3 key prefix for intermediate manifests and batch findings.
  MinEntityScore:
    Type: Number
    Default: 0.8
    Description: Minimum confidence score from Comprehend (0.0 to 1.0).
  ComprehendLanguage:
    Type: String
    Default: en
    AllowedValues:
      - en
      - es
    Description: Language code used for Comprehend PII detection.
  ChunkCharLimit:
    Type: Number
    Default: 4500
    Description: Max characters per text chunk sent to Comprehend.
  ChunksPerBatch:
    Type: Number
    Default: 20
    Description: Number of chunks grouped into one batch file.
  MapMaxConcurrency:
    Type: Number
    Default: 5
    Description: Parallel batch-processing concurrency in Step Functions Map state.
  EnableS3Authorship:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Whether S3-triggered pipeline also generates AI authorship report artifacts.
  EnableS3DocumentSummary:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Whether S3-triggered pipeline also generates document summary PDF artifacts.
  RequireS3Capabilities:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: If true, fail pipeline when authorship or summary generation fails.
  S3AuthorshipDetector:
    Type: String
    Default: heuristic
    AllowedValues:
      - heuristic
      - model
    Description: Detector used for S3-triggered authorship analysis.
  S3AuthorshipModel:
    Type: String
    Default: ""
    Description: Optional model name when S3AuthorshipDetector=model.
  S3SummaryModel:
    Type: String
    Default: ""
    Description: Optional model name for S3-triggered document summary generation.
  S3SummaryDirections:
    Type: String
    Default: ""
    Description: Optional additional directions appended to S3-triggered summary prompts.
  OpenAIApiKey:
    Type: String
    NoEcho: true
    Default: ""
    Description: Optional OpenAI API key for model-backed S3 capabilities.

Resources:
  PdfPipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  PdfRedactionStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${AWS::StackName}-pdf-redaction"
      Type: STANDARD
      DefinitionSubstitutions:
        PrepareChunksFunctionArn: !GetAtt PrepareChunksFunction.Arn
        DetectBatchFunctionArn: !GetAtt DetectBatchFunction.Arn
        AssembleOutputFunctionArn: !GetAtt AssembleOutputFunction.Arn
      Definition:
        Comment: Chunk large PDFs, detect PII in parallel batches, and build redacted outputs.
        StartAt: PrepareChunks
        States:
          PrepareChunks:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: ${PrepareChunksFunctionArn}
              Payload.$: $
            OutputPath: $.Payload
            Next: ProcessBatches
          ProcessBatches:
            Type: Map
            ItemsPath: $.batch_manifest_keys
            MaxConcurrencyPath: $.map_max_concurrency
            ItemSelector:
              job.$: $
              batch_manifest_key.$: $$.Map.Item.Value
            ItemProcessor:
              ProcessorConfig:
                Mode: INLINE
              StartAt: DetectBatch
              States:
                DetectBatch:
                  Type: Task
                  Resource: arn:aws:states:::lambda:invoke
                  Parameters:
                    FunctionName: ${DetectBatchFunctionArn}
                    Payload:
                      job_id.$: $.job.job_id
                      work_bucket.$: $.job.work_bucket
                      work_prefix.$: $.job.work_prefix
                      batch_manifest_key.$: $.batch_manifest_key
                      min_entity_score.$: $.job.min_entity_score
                      language_code.$: $.job.language_code
                  OutputPath: $.Payload
                  End: true
            ResultPath: $.batch_results
            Next: AssembleOutput
          AssembleOutput:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: ${AssembleOutputFunctionArn}
              Payload.$: $
            OutputPath: $.Payload
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref PrepareChunksFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref DetectBatchFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AssembleOutputFunction

  StartPipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: start_execution.lambda_handler
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref PdfRedactionStateMachine
          INPUT_PREFIX: !Ref InputPrefix
          OUTPUT_PREFIX: !Ref OutputPrefix
          REPORT_PREFIX: !Ref ReportPrefix
          WORK_PREFIX: !Ref WorkPrefix
          OUTPUT_BUCKET: !Ref PdfPipelineBucket
          MIN_ENTITY_SCORE: !Ref MinEntityScore
          COMPREHEND_LANGUAGE: !Ref ComprehendLanguage
          CHUNK_CHAR_LIMIT: !Ref ChunkCharLimit
          CHUNKS_PER_BATCH: !Ref ChunksPerBatch
          MAP_MAX_CONCURRENCY: !Ref MapMaxConcurrency
          ENABLE_S3_AUTHORSHIP: !Ref EnableS3Authorship
          ENABLE_S3_DOCUMENT_SUMMARY: !Ref EnableS3DocumentSummary
          REQUIRE_S3_CAPABILITIES: !Ref RequireS3Capabilities
          S3_AUTHORSHIP_DETECTOR: !Ref S3AuthorshipDetector
          S3_AUTHORSHIP_MODEL: !Ref S3AuthorshipModel
          S3_SUMMARY_MODEL: !Ref S3SummaryModel
          S3_SUMMARY_DIRECTIONS: !Ref S3SummaryDirections
          LOG_LEVEL: INFO
      Policies:
        - Statement:
            - Sid: AllowStartStateMachine
              Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Ref PdfRedactionStateMachine

  PrepareChunksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: prepare_chunks.lambda_handler
      Timeout: 900
      MemorySize: 3008
      Environment:
        Variables:
          WORK_PREFIX: !Ref WorkPrefix
          CHUNK_CHAR_LIMIT: !Ref ChunkCharLimit
          CHUNKS_PER_BATCH: !Ref ChunksPerBatch
          LOG_LEVEL: INFO
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PdfPipelineBucket

  DetectBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: detect_pii_batch.lambda_handler
      Timeout: 120
      MemorySize: 1024
      Environment:
        Variables:
          MIN_ENTITY_SCORE: !Ref MinEntityScore
          COMPREHEND_LANGUAGE: !Ref ComprehendLanguage
          LOG_LEVEL: INFO
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PdfPipelineBucket
        - Statement:
            - Sid: AllowComprehendPIIDetection
              Effect: Allow
              Action:
                - comprehend:DetectPiiEntities
              Resource: "*"

  AssembleOutputFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: assemble_output.lambda_handler
      Timeout: 900
      MemorySize: 3008
      Environment:
        Variables:
          INPUT_PREFIX: !Ref InputPrefix
          OUTPUT_PREFIX: !Ref OutputPrefix
          REPORT_PREFIX: !Ref ReportPrefix
          WORK_PREFIX: !Ref WorkPrefix
          OPENAI_API_KEY: !Ref OpenAIApiKey
          ENABLE_S3_AUTHORSHIP: !Ref EnableS3Authorship
          ENABLE_S3_DOCUMENT_SUMMARY: !Ref EnableS3DocumentSummary
          REQUIRE_S3_CAPABILITIES: !Ref RequireS3Capabilities
          S3_AUTHORSHIP_DETECTOR: !Ref S3AuthorshipDetector
          S3_AUTHORSHIP_MODEL: !Ref S3AuthorshipModel
          S3_SUMMARY_MODEL: !Ref S3SummaryModel
          S3_SUMMARY_DIRECTIONS: !Ref S3SummaryDirections
          LOG_LEVEL: INFO
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PdfPipelineBucket

  S3ObjectCreatedRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Start redaction pipeline for new objects in the pipeline bucket.
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref PdfPipelineBucket
      Targets:
        - Arn: !GetAtt StartPipelineFunction.Arn
          Id: StartPipelineTarget

  AllowEventBridgeInvokeStartPipeline:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StartPipelineFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt S3ObjectCreatedRule.Arn

Outputs:
  BucketName:
    Description: S3 bucket for input PDFs, redacted outputs, and reports.
    Value: !Ref PdfPipelineBucket
  InputPrefix:
    Description: Upload trigger prefix.
    Value: !Ref InputPrefix
  OutputPrefix:
    Description: Redacted PDF output prefix.
    Value: !Ref OutputPrefix
  ReportPrefix:
    Description: JSON report output prefix.
    Value: !Ref ReportPrefix
  WorkPrefix:
    Description: Intermediate processing prefix.
    Value: !Ref WorkPrefix
  StateMachineArn:
    Description: Step Functions state machine ARN.
    Value: !Ref PdfRedactionStateMachine
  StartFunctionName:
    Description: Lambda that starts state machine executions.
    Value: !Ref StartPipelineFunction
