AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  Event-driven AWS pipeline to chunk large PDFs, batch-process PII detection
  with Amazon Comprehend, and produce a fully redacted PDF plus redaction report.
# AWS GovCloud / NIST SP 800-53 implementation notes:
# - Validate that all services/models used are approved in your ATO boundary.
# - Typical control mapping for this stack includes AC-2/AC-3/AC-6, AU-2/AU-6/AU-9,
#   CM-2/CM-6, IA-2/IA-5, SC-7/SC-8/SC-12/SC-13/SC-28, and SI-4/SI-7.
# - This template is functional baseline infra; apply your agency SSP/ISSO hardening profile.

Globals:
  Function:
    Runtime: python3.12
    Tracing: Active
    Architectures:
      - x86_64
    # GovCloud hardening (SC-7): run Lambda in private subnets and route to AWS services
    # through VPC endpoints (S3, STS, CloudWatch Logs, X-Ray, Step Functions, Comprehend,
    # and Bedrock Runtime if used). Keep internet egress disabled unless explicitly authorized.
    Layers:
      - !Ref SharedDependenciesLayer

Parameters:
  InputPrefix:
    Type: String
    Default: incoming/
    Description: S3 key prefix where source PDFs are uploaded.
  OutputPrefix:
    Type: String
    Default: redacted/
    Description: S3 key prefix where redacted PDFs are written.
  ReportPrefix:
    Type: String
    Default: reports/
    Description: S3 key prefix where JSON redaction reports are written.
  WorkPrefix:
    Type: String
    Default: work/
    Description: S3 key prefix for intermediate manifests and batch findings.
  MinEntityScore:
    Type: Number
    Default: 0.8
    Description: Minimum confidence score from Comprehend (0.0 to 1.0).
  ComprehendLanguage:
    Type: String
    Default: en
    AllowedValues:
      - en
      - es
    Description: Language code used for Comprehend PII detection.
  ChunkCharLimit:
    Type: Number
    Default: 4500
    Description: Max characters per text chunk sent to Comprehend.
  ChunksPerBatch:
    Type: Number
    Default: 20
    Description: Number of chunks grouped into one batch file.
  MapMaxConcurrency:
    Type: Number
    Default: 5
    Description: Parallel batch-processing concurrency in Step Functions Map state.
  EnableS3Authorship:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Whether S3-triggered pipeline also generates AI authorship report artifacts.
  EnableS3DocumentSummary:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Whether S3-triggered pipeline also generates document summary PDF artifacts.
  RequireS3Capabilities:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: If true, fail pipeline when authorship or summary generation fails.
  S3AuthorshipDetector:
    Type: String
    Default: heuristic
    AllowedValues:
      - heuristic
      - model
    Description: Detector used for S3-triggered authorship analysis.
  S3AuthorshipModel:
    Type: String
    Default: ""
    Description: Optional model name when S3AuthorshipDetector=model.
  S3SummaryModel:
    Type: String
    Default: ""
    Description: Optional model name for S3-triggered document summary generation.
  S3SummaryDirections:
    Type: String
    Default: ""
    Description: Optional additional directions appended to S3-triggered summary prompts.
  OpenAIApiKey:
    Type: String
    NoEcho: true
    Default: ""
    # In production, prefer injecting this from Secrets Manager/SSM rather than plaintext parameter values.
    # GovCloud boundary note (SC-7/SA-9): OpenAI is an external provider path.
    # If your boundary disallows external AI APIs, keep this empty and use only `bedrock:*` models.
    Description: Optional OpenAI API key for model-backed S3 capabilities.

Resources:
  # GovCloud/NIST logging note (AU-11/AU-12):
  # Add explicit CloudWatch LogGroup resources with retention + KMS encryption for
  # each Lambda and the Step Functions state machine, rather than relying on defaults.
  SharedDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}-shared-dependencies"
      Description: Shared Python dependencies for PDF processing and model-backed capabilities.
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.12
      CompatibleArchitectures:
        - x86_64
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.12

  PdfPipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # For stricter SC-12/SC-13/SC-28 controls, prefer SSE-KMS with a customer-managed CMK
      # and key policy scoped to this workload role set.
      # Consider enabling bucket versioning/object lock per records-retention requirements.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  PdfRedactionStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${AWS::StackName}-pdf-redaction"
      Type: STANDARD
      # AU-2/AU-12: Step Functions execution history can be part of auditable evidence.
      # Configure CloudWatch Logs/X-Ray retention + encryption per your organizational policy.
      DefinitionSubstitutions:
        PrepareChunksFunctionArn: !GetAtt PrepareChunksFunction.Arn
        DetectBatchFunctionArn: !GetAtt DetectBatchFunction.Arn
        AssembleRedactionFunctionArn: !GetAtt AssembleRedactionFunction.Arn
        GenerateAuthorshipArtifactFunctionArn: !GetAtt GenerateAuthorshipArtifactFunction.Arn
        GenerateDocumentSummaryArtifactFunctionArn: !GetAtt GenerateDocumentSummaryArtifactFunction.Arn
        FinalizeReportFunctionArn: !GetAtt FinalizeReportFunction.Arn
      Definition:
        Comment: Chunk large PDFs, detect PII in parallel batches, and build redacted outputs.
        StartAt: PrepareChunks
        States:
          PrepareChunks:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: ${PrepareChunksFunctionArn}
              Payload.$: $
            OutputPath: $.Payload
            Next: ProcessBatches
          ProcessBatches:
            Type: Map
            ItemsPath: $.batch_manifest_keys
            MaxConcurrencyPath: $.map_max_concurrency
            ItemSelector:
              job.$: $
              batch_manifest_key.$: $$.Map.Item.Value
            ItemProcessor:
              ProcessorConfig:
                Mode: INLINE
              StartAt: DetectBatch
              States:
                DetectBatch:
                  Type: Task
                  Resource: arn:aws:states:::lambda:invoke
                  Parameters:
                    FunctionName: ${DetectBatchFunctionArn}
                    Payload:
                      job_id.$: $.job.job_id
                      work_bucket.$: $.job.work_bucket
                      work_prefix.$: $.job.work_prefix
                      batch_manifest_key.$: $.batch_manifest_key
                      min_entity_score.$: $.job.min_entity_score
                      language_code.$: $.job.language_code
                  OutputPath: $.Payload
                  End: true
            ResultPath: $.batch_results
            Next: AssembleRedaction
          AssembleRedaction:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: ${AssembleRedactionFunctionArn}
              Payload.$: $
            OutputPath: $.Payload
            Next: GenerateCapabilities
          GenerateCapabilities:
            Type: Parallel
            Branches:
              - StartAt: GenerateAuthorshipArtifact
                States:
                  GenerateAuthorshipArtifact:
                    Type: Task
                    Resource: arn:aws:states:::lambda:invoke
                    Parameters:
                      FunctionName: ${GenerateAuthorshipArtifactFunctionArn}
                      Payload.$: $
                    OutputPath: $.Payload
                    End: true
              - StartAt: GenerateDocumentSummaryArtifact
                States:
                  GenerateDocumentSummaryArtifact:
                    Type: Task
                    Resource: arn:aws:states:::lambda:invoke
                    Parameters:
                      FunctionName: ${GenerateDocumentSummaryArtifactFunctionArn}
                      Payload.$: $
                    OutputPath: $.Payload
                    End: true
            ResultPath: $.capability_results
            Next: FinalizeReport
          FinalizeReport:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: ${FinalizeReportFunctionArn}
              Payload.$: $
            OutputPath: $.Payload
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref PrepareChunksFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref DetectBatchFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AssembleRedactionFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GenerateAuthorshipArtifactFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GenerateDocumentSummaryArtifactFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FinalizeReportFunction
      # AC-6: Revisit this policy set and scope to least privilege when introducing
      # additional workflow steps or cross-account integrations.

  StartPipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: start_execution.lambda_handler
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref PdfRedactionStateMachine
          INPUT_PREFIX: !Ref InputPrefix
          OUTPUT_PREFIX: !Ref OutputPrefix
          REPORT_PREFIX: !Ref ReportPrefix
          WORK_PREFIX: !Ref WorkPrefix
          OUTPUT_BUCKET: !Ref PdfPipelineBucket
          MIN_ENTITY_SCORE: !Ref MinEntityScore
          COMPREHEND_LANGUAGE: !Ref ComprehendLanguage
          CHUNK_CHAR_LIMIT: !Ref ChunkCharLimit
          CHUNKS_PER_BATCH: !Ref ChunksPerBatch
          MAP_MAX_CONCURRENCY: !Ref MapMaxConcurrency
          ENABLE_S3_AUTHORSHIP: !Ref EnableS3Authorship
          ENABLE_S3_DOCUMENT_SUMMARY: !Ref EnableS3DocumentSummary
          REQUIRE_S3_CAPABILITIES: !Ref RequireS3Capabilities
          S3_AUTHORSHIP_DETECTOR: !Ref S3AuthorshipDetector
          S3_AUTHORSHIP_MODEL: !Ref S3AuthorshipModel
          S3_SUMMARY_MODEL: !Ref S3SummaryModel
          S3_SUMMARY_DIRECTIONS: !Ref S3SummaryDirections
          LOG_LEVEL: INFO
      Policies:
        - Statement:
            - Sid: AllowStartStateMachine
              Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Ref PdfRedactionStateMachine
      # AC-6: Keep permission to only this state machine ARN (already scoped).

  PrepareChunksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: prepare_chunks.lambda_handler
      Timeout: 900
      MemorySize: 3008
      Environment:
        Variables:
          WORK_PREFIX: !Ref WorkPrefix
          CHUNK_CHAR_LIMIT: !Ref ChunkCharLimit
          CHUNKS_PER_BATCH: !Ref ChunksPerBatch
          LOG_LEVEL: INFO
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PdfPipelineBucket
      # AC-6 note: S3CrudPolicy is broad for rapid setup; replace with prefix-scoped IAM statements
      # (`incoming/`, `work/`) in regulated deployments.

  DetectBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: detect_pii_batch.lambda_handler
      Timeout: 120
      MemorySize: 1024
      Environment:
        Variables:
          MIN_ENTITY_SCORE: !Ref MinEntityScore
          COMPREHEND_LANGUAGE: !Ref ComprehendLanguage
          LOG_LEVEL: INFO
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PdfPipelineBucket
        - Statement:
            - Sid: AllowComprehendPIIDetection
              Effect: Allow
              Action:
                - comprehend:DetectPiiEntities
              Resource: "*"
      # Comprehend DetectPiiEntities currently uses "*" resource scope by API design.
      # Document this exception in least-privilege reviews (AC-6) and monitor usage (AU-6).

  AssembleRedactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: assemble_redaction.lambda_handler
      Timeout: 900
      MemorySize: 3008
      Environment:
        Variables:
          INPUT_PREFIX: !Ref InputPrefix
          OUTPUT_PREFIX: !Ref OutputPrefix
          REPORT_PREFIX: !Ref ReportPrefix
          WORK_PREFIX: !Ref WorkPrefix
          ENABLE_S3_AUTHORSHIP: !Ref EnableS3Authorship
          ENABLE_S3_DOCUMENT_SUMMARY: !Ref EnableS3DocumentSummary
          REQUIRE_S3_CAPABILITIES: !Ref RequireS3Capabilities
          S3_AUTHORSHIP_DETECTOR: !Ref S3AuthorshipDetector
          S3_AUTHORSHIP_MODEL: !Ref S3AuthorshipModel
          S3_SUMMARY_MODEL: !Ref S3SummaryModel
          S3_SUMMARY_DIRECTIONS: !Ref S3SummaryDirections
          LOG_LEVEL: INFO
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PdfPipelineBucket
      # AC-6 note: replace S3CrudPolicy with prefix-scoped permissions in production.

  GenerateAuthorshipArtifactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: generate_authorship_artifact.lambda_handler
      Timeout: 900
      MemorySize: 3008
      Environment:
        Variables:
          INPUT_PREFIX: !Ref InputPrefix
          REPORT_PREFIX: !Ref ReportPrefix
          OPENAI_API_KEY: !Ref OpenAIApiKey
          ENABLE_S3_AUTHORSHIP: !Ref EnableS3Authorship
          REQUIRE_S3_CAPABILITIES: !Ref RequireS3Capabilities
          S3_AUTHORSHIP_DETECTOR: !Ref S3AuthorshipDetector
          S3_AUTHORSHIP_MODEL: !Ref S3AuthorshipModel
          LOG_LEVEL: INFO
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PdfPipelineBucket
        # NOTE: If S3AuthorshipModel uses `bedrock:*`, add IAM permissions for Bedrock runtime invocation.
        # Example actions: `bedrock:InvokeModel` (and optionally `bedrock:InvokeModelWithResponseStream`).
        # GovCloud/NIST note: if using OpenAI models here, treat as external system interconnection.

  GenerateDocumentSummaryArtifactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: generate_document_summary_artifact.lambda_handler
      Timeout: 900
      MemorySize: 3008
      Environment:
        Variables:
          INPUT_PREFIX: !Ref InputPrefix
          REPORT_PREFIX: !Ref ReportPrefix
          OPENAI_API_KEY: !Ref OpenAIApiKey
          ENABLE_S3_DOCUMENT_SUMMARY: !Ref EnableS3DocumentSummary
          REQUIRE_S3_CAPABILITIES: !Ref RequireS3Capabilities
          S3_SUMMARY_MODEL: !Ref S3SummaryModel
          S3_SUMMARY_DIRECTIONS: !Ref S3SummaryDirections
          LOG_LEVEL: INFO
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PdfPipelineBucket
        # NOTE: If S3SummaryModel uses `bedrock:*`, add IAM permissions for Bedrock runtime invocation.
        # Example actions: `bedrock:InvokeModel` (and optionally `bedrock:InvokeModelWithResponseStream`).
        # GovCloud/NIST note: if using OpenAI models here, treat as external system interconnection.

  FinalizeReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: finalize_report.lambda_handler
      Timeout: 900
      MemorySize: 1024
      Environment:
        Variables:
          WORK_PREFIX: !Ref WorkPrefix
          REQUIRE_S3_CAPABILITIES: !Ref RequireS3Capabilities
          LOG_LEVEL: INFO
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PdfPipelineBucket
      # AC-6 note: replace S3CrudPolicy with prefix-scoped permissions in production.

  S3ObjectCreatedRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Start redaction pipeline for new objects in the pipeline bucket.
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref PdfPipelineBucket
      Targets:
        - Arn: !GetAtt StartPipelineFunction.Arn
          Id: StartPipelineTarget

  AllowEventBridgeInvokeStartPipeline:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StartPipelineFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt S3ObjectCreatedRule.Arn

Outputs:
  BucketName:
    Description: S3 bucket for input PDFs, redacted outputs, and reports.
    Value: !Ref PdfPipelineBucket
  InputPrefix:
    Description: Upload trigger prefix.
    Value: !Ref InputPrefix
  OutputPrefix:
    Description: Redacted PDF output prefix.
    Value: !Ref OutputPrefix
  ReportPrefix:
    Description: JSON report output prefix.
    Value: !Ref ReportPrefix
  WorkPrefix:
    Description: Intermediate processing prefix.
    Value: !Ref WorkPrefix
  StateMachineArn:
    Description: Step Functions state machine ARN.
    Value: !Ref PdfRedactionStateMachine
  StartFunctionName:
    Description: Lambda that starts state machine executions.
    Value: !Ref StartPipelineFunction
